/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
    T & {
        _key: string;
    }
>;

// Source: schema.json
export type ExhibitionText = {
    _id: string;
    _type: 'exhibitionText';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    author?: string;
    body?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?: 'normal' | 'blockquote';
        listItem?: never;
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
};

export type SanityImageAssetReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type PosterInfo = {
    _id: string;
    _type: 'posterInfo';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    artist?: string;
    title?: string;
    yearStart?: number;
    yearEnd?: number;
    artwork?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: 'image';
    };
    visiting?: Array<{
        children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: 'span';
            _key: string;
        }>;
        style?: 'normal';
        listItem?: never;
        markDefs?: Array<{
            href?: string;
            _type: 'link';
            _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
    }>;
};

export type SanityImageCrop = {
    _type: 'sanity.imageCrop';
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
};

export type SanityImageHotspot = {
    _type: 'sanity.imageHotspot';
    x?: number;
    y?: number;
    height?: number;
    width?: number;
};

export type TourReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'tour';
};

export type TourDateReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'tourDate';
};

export type ReleaseReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'release';
};

export type VideoReference = {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'video';
};

export type NewPosts = {
    _id: string;
    _type: 'newPosts';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    posts?: ArrayOf<TourReference | TourDateReference | ReleaseReference | VideoReference>;
};

export type TourDate = {
    _id: string;
    _type: 'tourDate';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    artist?: string;
    date?: string;
    dateEnd?: string;
    location?: string;
    venue?: string;
    links?: Array<{
        label?: string;
        url?: string;
        _type: 'link';
        _key: string;
    }>;
};

export type Video = {
    _id: string;
    _type: 'video';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    artist?: string;
    date?: string;
    links?: Array<{
        label?: string;
        url?: string;
        _type: 'link';
        _key: string;
    }>;
};

export type Tour = {
    _id: string;
    _type: 'tour';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    artist?: string;
    region?: string;
    date?: string;
    links?: Array<{
        label?: string;
        url?: string;
        _type: 'link';
        _key: string;
    }>;
};

export type Release = {
    _id: string;
    _type: 'release';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    type?: string;
    artist?: string;
    date?: string;
    links?: Array<{
        label?: string;
        url?: string;
        _type: 'link';
        _key: string;
    }>;
};

export type About = {
    _id: string;
    _type: 'about';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    contactEmail?: string;
    contactLinks?: Array<{
        label?: string;
        url?: string;
        _key: string;
    }>;
};

export type SanityImagePaletteSwatch = {
    _type: 'sanity.imagePaletteSwatch';
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: 'sanity.imagePalette';
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: 'sanity.imageDimensions';
    height?: number;
    width?: number;
    aspectRatio?: number;
};

export type SanityImageMetadata = {
    _type: 'sanity.imageMetadata';
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    thumbHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type SanityFileAsset = {
    _id: string;
    _type: 'sanity.fileAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
    _type: 'sanity.assetSourceData';
    name?: string;
    id?: string;
    url?: string;
};

export type SanityImageAsset = {
    _id: string;
    _type: 'sanity.imageAsset';
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type Geopoint = {
    _type: 'geopoint';
    lat?: number;
    lng?: number;
    alt?: number;
};

export type Slug = {
    _type: 'slug';
    current?: string;
    source?: string;
};

export type AllSanitySchemaTypes =
    | ExhibitionText
    | SanityImageAssetReference
    | PosterInfo
    | SanityImageCrop
    | SanityImageHotspot
    | TourReference
    | TourDateReference
    | ReleaseReference
    | VideoReference
    | NewPosts
    | TourDate
    | Video
    | Tour
    | Release
    | About
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityImageMetadata
    | SanityFileAsset
    | SanityAssetSourceData
    | SanityImageAsset
    | Geopoint
    | Slug;
